# Generated by Django 3.2.6 on 2021-08-27 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerceapp', '0002_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phonenumber',
            field=models.IntegerField(default=2, max_length=11),
            preserve_default=False,
        ),
    ]
