# Generated by Django 3.2.6 on 2021-08-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerceapp', '0003_customer_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phonenumber',
            field=models.IntegerField(),
        ),
    ]
